/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function PiggyBank(props) {
  const { nodes, materials } = useGLTF("/PiggyBank.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pasted__Piggy_Bank001.geometry}
        material={materials.Pig}
        position={[0, -1.5, 0]}
        rotation={[0, 0.56, 0]}
        scale={0.04}
      />
    </group>
  );
}

useGLTF.preload("/PiggyBank.glb");
