/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function SignBoard(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/SignBoard.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Cylinder"
          position={[0,-0.8,0]}
          rotation={[0, 0.6, 0]}
          scale={0.12}
        >
          <mesh
            name="Cylinder_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials["Yellow stone"]}
          />
          <mesh
            name="Cylinder_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2.geometry}
            material={materials["Sign board"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/SignBoard.glb");
