/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";


const deg2rad = degrees => degrees * (Math.PI / 180);

export default function Factory(props) {
  const { nodes, materials } = useGLTF("/Factory.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0, 0]}
        rotation={[3, 1.03, -3.05]}
        scale={0.09}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh053.geometry}
          material={materials.Walls}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh053_1.geometry}
          material={materials.Windows}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh053_2.geometry}
          material={materials["Sliding door"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh053_3.geometry}
          material={materials.Borders}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh053_4.geometry}
          material={materials.Door}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh053_5.geometry}
          material={materials["More chimneys"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh053_6.geometry}
          material={materials.Smoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh053_7.geometry}
          material={materials.Chimneys}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh053_8.geometry}
          material={materials.Stairs}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Factory.glb");
