/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Benefits(props) {
  const { nodes, materials } = useGLTF("/Benefits.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -1.5, 0]}
        rotation={[0.69182672, 0.12655814, 0.25218323]}
        scale={[0.07854235, 0.07854234, 0.07854234]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017.geometry}
          material={materials.Hands}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_1.geometry}
          material={materials["pasted__Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_2.geometry}
          material={materials["pasted__Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_3.geometry}
          material={materials["pasted__Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_4.geometry}
          material={materials["pasted__Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_5.geometry}
          material={materials["pasted__Material.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_6.geometry}
          material={materials.he}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_7.geometry}
          material={materials["pasted__Material.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_8.geometry}
          material={materials["pasted__Material.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_9.geometry}
          material={materials["pasted__Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_10.geometry}
          material={materials["pasted__Material.033"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_11.geometry}
          material={materials.pasted__Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_12.geometry}
          material={materials["pasted__Material.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_13.geometry}
          material={materials["pasted__Material.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_14.geometry}
          material={materials.Coin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_15.geometry}
          material={materials.pasted__lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_16.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh017_17.geometry}
          material={materials["Material.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Benefits.glb");
