/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";


export default function Gear(props) {
  const { nodes, materials } = useGLTF("/Gear.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.Gear}
        position={[0, 0, 0]}
        rotation={[1.4, 0, -0.7]}
        scale={[1.68, 0.31, 1.68]}
      />
    </group>
  );
}

useGLTF.preload("/Gear.glb");
