/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Land(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/FreeLand.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="pCube13"
          position={[0, 0, 0.5]}
          rotation={[3.3, 0, 0.98]}
          scale={[3.08, 3.08, 0.12]}
        >
          <mesh
            name="Mesh001"
            castShadow
            receiveShadow
            geometry={nodes.Mesh001.geometry}
            material={materials.Material}
          />
          <mesh
            name="Mesh001_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh001_1.geometry}
            material={materials.lambert1}
          />
          <mesh
            name="Mesh001_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh001_2.geometry}
            material={materials["lambert1.001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/FreeLand.glb");
